# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: WFNW45c23Ch9NX6uamDp52rHx9puXft6J491SbqbWUIYw1I90geSNUUrK4gNagr
  expiration: 604800
  route:
    authentication:
      login: auth/login
      refresh: auth/refresh
      register: auth/register

#logging:
#  level:
#    org.springframework:
#      security: DEBUG